version: '3.8'

services:
  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app

  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf