version: '3.9'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: "mahdi"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "LibraryApp"
      MYSQL_PASSWORD: "1234"
    healthcheck:
        test: "mysqladmin ping -h localhost"
        interval: 1s
        timeout: 20s
        retries: 10
        start_period: 0.1s
      
  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: mahdi2359/testproj_flask
    restart: always
    volumes:
      - ./app:/app
    depends_on:
          mysql:
            condition: service_healthy
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: mahdi2359/testproj_nginx
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf